name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name : Récupération du code
        uses: actions/checkout@v4

      - name: Configurer Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name : Inject keys and secret config
        env :
          GOOGLE_SERVICES_JSON_B64: ${{ secrets.GOOGLE_SERVICES_JSON }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run : |
          echo "$GOOGLE_SERVICES_JSON_B64" | base64 -d > app/google-services.json
          echo "google.maps.key=$MAPS_API_KEY" > local.properties

      - name: Build with Gradle version debug
        run: ./gradlew assembleDebug

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests unit, instrumented,
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name : generate Jacoco Report
        run : ./gradlew jacocoReport

      - name : publish Jacoco Report
        uses : actions/upload-artifact@v4
        with :
            name : jacoco-report
            path : app/build/reports/jacoco/jacocoCombinedReport/html