name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name : Récupération du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurer Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Inject keys and secret config
        env:
          GOOGLE_SERVICES_JSON_B64: ${{ secrets.GOOGLE_SERVICES_JSON }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          echo "$GOOGLE_SERVICES_JSON_B64" | base64 -d > app/google-services.json
          echo "google.maps.key=$MAPS_API_KEY" > local.properties

      - name: Build with Gradle version debug
        run: ./gradlew assembleDebug

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests unit, instrumented, and cover
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck jacocoReport

      - name: save reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Reports-Tests-Android
          path: app/build/reports/

      - name: Cache SonarQube
        uses : actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Envoyer l'analyse et le rapport JaCoCo à SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info
